### ISSUE TITLE
portalpy Vs ArcGIS Python API (for Portal Admin)

### ISSUE THREAD

**Issue by jakc** [Esri/portalpy#23]
Apologies for raising this on Github, as not really an issue, but wanted to target your ears.

What is the recommended path for developing scripts for administering a Portal?

The [ArcGIS Python API has samples that perform administration](https://developers.arcgis.com/python/sample-notebooks/clone-portal-users-groups-and-content/) and of course PortalPy is dedicated for administering a Portal.

1. Any pros/cons of each approach?  
2. Will portalpy be ported to support v3 Python?
3. Is their a roadmap from Esri about which one is more likely to prevail?

**Comment by rwmajor2** [comment]
@jakc Thanks for the note.  As an Esri staffer, I would urge you to start using the ArcGIS Python API as the path forward.  Portalpy is/was a great Python toolset, but wasn't actively maintained on GitHub and its future is uncertain.  The ArcGIS Python API, on the other hand, has resources and efforts being dedicated to it to continue to build that out.

It would be interesting to know what types of portalpy scripts you have developed for administration. One of the things we are trying to make sure is that the ArcGIS Python API has all of the capabilities as portalpy, so it would be a good use case to compare.

Thanks.

**Comment by jakc** [comment]
Appreciate the quick response.   Will pass on the info to some of our python gurus over here in Australia.
