### ISSUE TITLE
Mark this repository as deprecated

### ISSUE THREAD

**Issue by sverkerEsriSE** [Esri/portalpy#27]
I got this suggestions from one of our customers who tried using portalpy for some task (I instead helped him complete the task in ArcGIS API for Python).

The customer suggested that this repo is marked as deprecated and/or set to read-only.

I'm not sure what's possible in github officially, but some suggestions can be found here:
https://medium.com/maintainer-io/how-to-deprecate-a-repository-on-github-8f0ceb9155e

Best regards,
Sverker
Esri Sweden support team

**Comment by pheede** [comment]
@sverkerEsriSE the very first paragraph of the readme states this: "It has been superseded by the ArcGIS API for Python, but is left as a resource for anyone with existing dependencies."

**Comment by sverkerEsriSE** [comment]
Indeed it does. I just read the first sentence, so now I feel stupid!
Thanks for the reply!
